server:
  port: 8888

application:
  security:
    jwt:
      secret-key: MmRjNGY5NGMtNTVmMS00ZWVlLTg3NjctNDBiMjlmOWEyM2Q4
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:mysql://82.156.27.61:3306/easy_export_excel?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: daoying
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql